### ISSUE TITLE
Minor bugs in merge_sumstats code?

### ISSUE THREAD

**Issue by nievergeltlab** [LizaDarrous/lhcMR#2]
Hi, thanks for writing this cool software. I am testing it out now. There seem to be some missing commas in the array access statements in the command, namely:

Line 36: LDfile = LDfile[LDfile_ind]

But line 36 should be 
LDfile = LDfile[LDfile_ind,]

Similarly, the subsequent if statements require commas, i.e.

  if("MAF" %in% colnames(Xfile)){
    Xfile_ind = which(Xfile$MAF>mafT)
    Xfile = Xfile[Xfile_ind]
  }
  if("MAF" %in% colnames(Yfile)){
    Yfile_ind = which(Yfile$MAF>mafT)
    Yfile = Yfile[Yfile_ind]
  }
  if("INFO" %in% colnames(Xfile)){
    Xfile_ind = which(Xfile$INFO>infoT)
    Xfile = Xfile[Xfile_ind]
  }
  if("INFO" %in% colnames(Yfile)){
    Yfile_ind = which(Yfile$INFO>infoT)
    Yfile = Yfile[Yfile_ind]
  }

Xfile = Xfile[Xfile_ind] should instead be e.g.  Xfile = Xfile[Xfile_ind,]

Also, the inner_join command that is invoked seems to be from dplyr, but that package is not loaded with lhcMR.

best
adam

**Comment by LizaDarrous** [comment]
Hi Adam! 
Super appreciative of catching that while testing out the package! Have updated the code now.
I import inner_join from dplyr, it's one of the first packages I import since I used it so much, not sure if it gave you some sort of error? 
Let me know if it did or if there's anything issues you find, thank you!

**Comment by LizaDarrous** [comment]
Awesome, thanks again!
