### ISSUE TITLE
Error in calculate_SP()

### ISSUE THREAD

**Issue by zl2860** [LizaDarrous/lhcMR#6]
Hi Liza,

Thank you for developing the fantastic tool for MR analysis! Recently I am testing the codes and find a problem on running the function calculate_SP().  After preparing the data and putting them into the function, it returns the following error:

Munging exposure and outcome data FOR LDSC: 
Error in file$effect[[1]] : subscript out of bounds

I suspect the error is due to some sort of data format issues, so then I checked the related functions. The problem may be due to  the script`gettingSP_ldscMR.R`  (line47-49), where the function GenomicSEM::munge cannot identify the BETA column (named as `unstdb`) of the dataframe `X_filtered`, as the following error (from GenomicSEM::munge) shows:

"Cannot find beta or effect column, try renaming it effect in the summary statistics file for:EXP_GWAS.txt"

Same issues may also exist for the outcome GWAS dataframe.
I would like to apply this great tool in my research, but any solution for this problem? Thanks!

Adobe

**Comment by LizaDarrous** [comment]
Hello,

Thank you for your interest in our method! Thanks as well for digging in to find the possible cause of the bug.
It seems that the needed headers for GenomisSEM::munge are not there. In the previous step, lhcMR attempts to prepare the files and munge them so that the original effect (beta) is renamed to unstdb (unstanderdised beta), and an new column is calculated from the tstat and sample size to get the standardised effect column (now called beta and used in further steps). 
In the column you provide, are beta, se, and sample size all present?

Best,
Liza
